### ISSUE TITLE
Add test pages

### ISSUE THREAD

**Issue by giridhar7632** [giridhar7632/osy-assistant#3]
tests about information of out-of-school youth
- question page and select the answer
- result page
    - share
    - show the needed help depends on answer

- `/test/osy-help`
- `/test/result`
- `/test/osy-basic-info`

**Comment by koremp** [comment]
`/test/osy-basic-info`
- starting page

`/test/osy-test`
- questions

`/test/result`
- result and share

**Comment by giridhar7632** [comment]
Hey @koremp 
I added the functionality with minimal UI. So we have to decide the questionnaire and what to display the results on the `result` page
